[LOCAL]
spark.app.name=retail-local
[TEST]
spark.app.name=retail-testspark.executor.instances=3spark.executor.cores=5spark.executor.memory=15GB
[PROD]
spark.app.name=retail-prodspark.executor.instances=3spark.executor.cores=5spark.executor.memory=4GB